"""create healthcare tables

Revision ID: afc6c33471a1
Revises: 
Create Date: 2026-03-06 07:07:57.515560
"""
from alembic import op
import sqlalchemy as sa


revision = 'afc6c33471a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nhs_healthcare_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'GP', 'SPECIALIST', 'LAB', 'PHARMACY', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nhs_healthcare_id'), 'user', ['nhs_healthcare_id'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('gpvisit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('gp_user_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_hidden_by_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gp_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpvisit_created_at'), 'gpvisit', ['created_at'], unique=False)
    op.create_index(op.f('ix_gpvisit_gp_user_id'), 'gpvisit', ['gp_user_id'], unique=False)
    op.create_index(op.f('ix_gpvisit_patient_user_id'), 'gpvisit', ['patient_user_id'], unique=False)
    op.create_table('laborder',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('test_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laborder_patient_user_id'), 'laborder', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_laborder_requested_by_user_id'), 'laborder', ['requested_by_user_id'], unique=False)
    op.create_table('medicationorder',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('prescribed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('dosage_instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicationorder_patient_user_id'), 'medicationorder', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_medicationorder_prescribed_by_user_id'), 'medicationorder', ['prescribed_by_user_id'], unique=False)
    op.create_table('patientprofile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('specialistreferral',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_user_id', sa.String(length=36), nullable=False),
    sa.Column('referred_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('specialist_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialistreferral_patient_user_id'), 'specialistreferral', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_specialistreferral_referred_by_user_id'), 'specialistreferral', ['referred_by_user_id'], unique=False)
    op.create_table('labreport',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_order_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_order_id'], ['laborder.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labreport_lab_order_id'), 'labreport', ['lab_order_id'], unique=False)
    op.create_index(op.f('ix_labreport_uploaded_by_user_id'), 'labreport', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labreport_uploaded_by_user_id'), table_name='labreport')
    op.drop_index(op.f('ix_labreport_lab_order_id'), table_name='labreport')
    op.drop_table('labreport')
    op.drop_index(op.f('ix_specialistreferral_referred_by_user_id'), table_name='specialistreferral')
    op.drop_index(op.f('ix_specialistreferral_patient_user_id'), table_name='specialistreferral')
    op.drop_table('specialistreferral')
    op.drop_table('patientprofile')
    op.drop_index(op.f('ix_medicationorder_prescribed_by_user_id'), table_name='medicationorder')
    op.drop_index(op.f('ix_medicationorder_patient_user_id'), table_name='medicationorder')
    op.drop_table('medicationorder')
    op.drop_index(op.f('ix_laborder_requested_by_user_id'), table_name='laborder')
    op.drop_index(op.f('ix_laborder_patient_user_id'), table_name='laborder')
    op.drop_table('laborder')
    op.drop_index(op.f('ix_gpvisit_patient_user_id'), table_name='gpvisit')
    op.drop_index(op.f('ix_gpvisit_gp_user_id'), table_name='gpvisit')
    op.drop_index(op.f('ix_gpvisit_created_at'), table_name='gpvisit')
    op.drop_table('gpvisit')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_nhs_healthcare_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
