"""add_health_ai_calendar_tables

Revision ID: fa3d5634185f
Revises: afc6c33471a1
Create Date: 2026-03-12 16:17:18.907153
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa3d5634185f'
down_revision = 'afc6c33471a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarevent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarevent_event_date'), 'calendarevent', ['event_date'], unique=False)
    op.create_index(op.f('ix_calendarevent_user_id'), 'calendarevent', ['user_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_user_id'), 'chatmessage', ['user_id'], unique=False)
    op.create_table('dietplan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('food_items', sa.Text(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dietplan_user_id'), 'dietplan', ['user_id'], unique=False)
    op.create_table('exerciseschedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.String(length=15), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exerciseschedule_user_id'), 'exerciseschedule', ['user_id'], unique=False)
    op.create_table('healthdatafile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('parsed_status', sa.String(length=20), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthdatafile_user_id'), 'healthdatafile', ['user_id'], unique=False)
    op.create_table('healthmetric',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.Enum('STEPS', 'HEART_RATE', 'CALORIES', 'SLEEP_HOURS', 'WEIGHT', 'BLOOD_PRESSURE', 'DISTANCE_KM', 'ACTIVE_MINUTES', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'FILE', 'APP', name='metricsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthmetric_metric_type'), 'healthmetric', ['metric_type'], unique=False)
    op.create_index(op.f('ix_healthmetric_recorded_date'), 'healthmetric', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_healthmetric_user_id'), 'healthmetric', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthmetric_user_id'), table_name='healthmetric')
    op.drop_index(op.f('ix_healthmetric_recorded_date'), table_name='healthmetric')
    op.drop_index(op.f('ix_healthmetric_metric_type'), table_name='healthmetric')
    op.drop_table('healthmetric')
    op.drop_index(op.f('ix_healthdatafile_user_id'), table_name='healthdatafile')
    op.drop_table('healthdatafile')
    op.drop_index(op.f('ix_exerciseschedule_user_id'), table_name='exerciseschedule')
    op.drop_table('exerciseschedule')
    op.drop_index(op.f('ix_dietplan_user_id'), table_name='dietplan')
    op.drop_table('dietplan')
    op.drop_index(op.f('ix_chatmessage_user_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_calendarevent_user_id'), table_name='calendarevent')
    op.drop_index(op.f('ix_calendarevent_event_date'), table_name='calendarevent')
    op.drop_table('calendarevent')
    # ### end Alembic commands ###
